### PR TITLE
Add ROS 2 snap entry

### PR DESCRIPTION
**Pull request by artivis**
Hey,
Not sure if this entry belong to the `containerization` section or possibly a new `packaging` section. Maybe is it better to move it to `documentation` since it points to a doc website.
Let me know what you prefer.

### CODE REVIEW

**Comment by fkromer** [comment]
Hi @artivis, I‘d go with a new packaging section.

**Comment by artivis** [comment]
Done.

**Review by fkromer — CHANGES_REQUESTED** [review]
Change level of section to ##, move `## Packaging` after `## Operatings Systems` and add packaging to `## Contents` pls.

**Comment by artivis** [comment]
Done :+1:

**Review by fkromer — APPROVED** [review]

**Pull request merged**
